config/routes.rb
BugId::Application.routes.draw do
  resources :bugs

  root :to => "bugs#index"
end

app/models/bug.rb
class Bug < ActiveRecord::Base
  attr_accessible :description, :status

  STATUS = ['Open', 'Closed']

  validates :description, :presence => true

  validates :status, :presence => true
  validates_inclusion_of :status, :in => STATUS
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/bugs_controller.rb
class BugsController < ApplicationController
  def index
    @bugs = Bug.all.sort_by(&:status).reverse
  end

  def new
    @bug = Bug.new(:status => 'Open')
  end

  def create
    @bug = Bug.new(params[:bug])

    if @bug.save
      redirect_to(bugs_path, :notice => 'Bug was successfully created.')
    else
      render :action => "new"
    end
  end

  def edit
    @bug = Bug.find(params[:id])
  end

  def update
    @bug = Bug.find(params[:id])

    respond_to do |format|
      if @bug.update_attributes(params[:bug])
        format.html { redirect_to(bugs_path, :notice => 'Post was successfully updated.') }
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bugs/_form.html.haml
=form_for(@bug) do |form|
  .field
    =form.label :description
    %br
    =form.text_area :description
  .field
    =form.label :status
    %br
    =form.select(:status, Bug::STATUS)
  .actions
    =form.submit
%br
  =link_to 'Back', bugs_path

app/views/bugs/edit.html.haml
%h2 Editing a bug

=render :partial => 'bugs/form'

app/views/bugs/index.html.haml
%h2 All Bugs

%table.bugs{:border=>1, :cellspacing=>0, :cellpadding=>4}
  %tr
    %th ID
    %th Description
    %th Status
    %th
  -@bugs.each do |bug|
    %tr{:index =>"bug-#{bug.id}", :class => 'bug'}
      %td.id= bug.id
      %td.description= bug.description
      %td.status= bug.status
      %td.edit= link_to 'Edit', edit_bug_path(bug)
%br
=link_to 'New Bug', new_bug_path

app/views/bugs/new.html.haml
%h2 New Bug

=render :partial => 'bugs/form'

app/views/layouts/_header.html.haml
.header
  %h1 Bug Id
  .navigation
    [
    %a{:title => 'Home', :href => bugs_path} Home
    ]

app/views/layouts/application.html.haml
!!! html5
%html
  %head
    %title BugId
    =stylesheet_link_tag :all
  %body
    =render :partial => 'layouts/header'
    #wrapper
      = yield